version: "2"
services:
  db-adt:
    image: postgres:9.3
    volumes:
      - "/home/openeobs/adt-connector/setupPGSQLForAdt.sql:/docker-entrypoint-initdb.d/setupPGSQLForAdt.sql"
    links:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"
